// Generated by Xata Codegen 0.26.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "post",
    columns: [
      { name: "title", type: "text" },
      { name: "body", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Post = InferredTypes["post"];
export type PostRecord = Post & XataRecord;

export type DatabaseSchema = {
  post: PostRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://robertmalyon-s-workspace-a4tqi3.eu-west-1.xata.sh/db/liver",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
